# CORE
GITHUB_RAW=https://raw.githubusercontent.com
GITHUB_API=https://api.github.com

# AI
OLLAMA=https://ollama.com
HF_MODELS=https://huggingface.co

# ANDROID
MAGISK=https://github.com/topjohnwu/Magisk/releases/latest
PLATFORM_TOOLS=https://dl.google.com/android/repository/platform-tools-latest-linux.zip

# PENTEST
KALI=https://archive.kali.org
SECLISTS=https://github.com/danielmiessler/SecLists

# CONTAINERS
DOCKER=https://get.docker.com
