#!/usr/bin/env python3
# git_autocommit.py
# Po codegenu inicializuje git repo v cílové složce, vytvoří commit a volitelně pushne.
# Pokud chceš push přes PAT, exportuj GITHUB_TOKEN do prostředí (bez uvozovek).
# Alternativně použij gh CLI (gh auth login).

import os
import subprocess
from pathlib import Path

def run(cmd, cwd=None):
    return subprocess.run(cmd, shell=True, cwd=cwd, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

def ensure_git_and_push(target_dir, remote_url=None, branch="main", commit_msg="Generated by AI Project Analyzer", push=True):
    p = Path(target_dir)
    if not p.exists():
        raise FileNotFoundError(target_dir)
    # init repo if not
    if not (p / ".git").exists():
        run("git init", cwd=str(p))
    run("git add -A", cwd=str(p))
    run(f"git commit -m \"{commit_msg}\" || true", cwd=str(p))
    if remote_url:
        run(f"git remote remove origin || true", cwd=str(p))
        run(f"git remote add origin {remote_url}", cwd=str(p))
    if push:
        # try to use gh if available
        if shutil_which("gh"):
            run(f"gh repo create {remote_url.split('/')[-2]}/{remote_url.split('/')[-1].replace('.git','')} --public --source=. --push", cwd=str(p))
        else:
            # push via token-based remote if GITHUB_TOKEN provided
            token = os.getenv("GITHUB_TOKEN")
            if token and remote_url and remote_url.startswith("https://"):
                # embed token in remote (only in memory) - caution
                push_url = remote_url.replace("https://", f"https://{token}@")
                run(f"git push -u {push_url} {branch}", cwd=str(p))
            elif remote_url:
                run(f"git push -u origin {branch}", cwd=str(p))
            else:
                print("No remote provided; commit only (no push).")

def shutil_which(cmd):
    from shutil import which
    return which(cmd)

if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("target_dir")
    ap.add_argument("--remote", default=None)
    ap.add_argument("--no-push", dest="push", action="store_false")
    args = ap.parse_args()
    ensure_git_and_push(args.target_dir, remote_url=args.remote, push=args.push)
